def mostrar_info_sistema():
    print("\n" + "="*60)
    print("INFORMACIÓN DEL SISTEMA")
    print("="*60)
    print("Proyecto: Simulador de Brazo Robótico 4DOF")
    print("\nCaracterísticas:")
    print("  • 4 Grados de libertad (articulaciones rotacionales)")
    print("  • Cinemática directa implementada (tradicional + matrices DH)")
    print("  • Interpolación de trayectorias suaves")
    print("  • Detección avanzada de colisiones:")
    print("    - Auto-colisiones con radios distintos")
    print("    - Verificación en ruta durante interpolación")
    print("  • Validación de límites operacionales")
    print("  • Visualización 3D con matplotlib")
    print("  • Persistencia de datos (JSON y CSV)")
    print("  • Registro y reproducción de secuencias")
    print("\nFormatos de archivo soportados:")
    print("  • JSON: Estructura completa con metadatos")
    print("  • CSV: Editable en Excel/Sheets, ideal para análisis")
    print("\nEspecificaciones técnicas:")
    print("  • Longitud Base: 2 unidades (radio: 1.0)")
    print("  • Longitud Hombro: 10 unidades (radio: 0.8)")
    print("  • Longitud Codo: 8 unidades (radio: 0.6)")
    print("  • Longitud Muñeca: 4 unidades (radio: 0.4)")
    print("  • Alcance máximo: 24 unidades")
    print("\nLímites angulares:")
    print("  • Base: -180° a +180°")
    print("  • Hombro: -70° a +70° (0° = vertical, evita contacto con suelo)")
    print("  • Codo: -135° a +135°")
    print("  • Muñeca: -135° a +135°")
    print("\nDesarrollado por: Sabas Garduño Gael")
    print("Materia: Fundamentos de Programación")
    print("Grupo: 1CM02")
    print("ESIMEZ - IPN")
    print("Fecha: Diciembre 2025")
    print("Versión: 1.1.0")
    print("="*60)


# Sabas Garduño Gael
# Fundamentos de Programación
# ESIME Zacatenco